testing with variables

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -90,37 +90,37 @@ jobs:
 
       - name: Deploy Amazon ECS task definition (Create if needed)
         id: deploy-task
-        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
         with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
           cluster: deployment-cluster
-          wait-for-service-stability: true
+          run-task: true
         continue-on-error: true
 
-      - name: Run ECS Task
-        run: |
-          TASK_ARN=$(aws ecs run-task \
-            --cluster deployment-cluster \
-            --task-definition deployment-task \
-            --launch-type FARGATE \
-            --query "tasks[0].taskArn" \
-            --output text \
-            --network-configuration "awsvpcConfiguration={subnets=[subnet-050c7a1e30ae0ba67,subnet-08587efdb6f603316,subnet-07085150e64d7ec70,subnet-02e3b5058d5807378,subnet-0549c111da38470b3,subnet-0fb8e6943c9a576b0],securityGroups=[sg-05ffdaea6df8038f0],assignPublicIp=ENABLED}" | tr -d '\n')
+      # - name: Run ECS Task
+      #   run: |
+      #     TASK_ARN=$(aws ecs run-task \
+      #       --cluster deployment-cluster \
+      #       --task-definition deployment-task \
+      #       --launch-type FARGATE \
+      #       --query "tasks[0].taskArn" \
+      #       --output text \
+      #       --network-configuration "awsvpcConfiguration={subnets=[subnet-050c7a1e30ae0ba67,subnet-08587efdb6f603316,subnet-07085150e64d7ec70,subnet-02e3b5058d5807378,subnet-0549c111da38470b3,subnet-0fb8e6943c9a576b0],securityGroups=[sg-05ffdaea6df8038f0],assignPublicIp=ENABLED}" | tr -d '\n')
 
-          echo "Debug: TASK_ARN=[$TASK_ARN]"
+      #     echo "Debug: TASK_ARN=[$TASK_ARN]"
 
-          aws ecs wait tasks-stopped --cluster deployment-cluster --tasks $TASK_ARN
+      #     aws ecs wait tasks-stopped --cluster deployment-cluster --tasks $TASK_ARN
 
-          TASK_STATUS=$(aws ecs describe-tasks --cluster deployment-cluster --tasks $TASK_ARN --query 'tasks[0].lastStatus' --output text)
+      #     TASK_STATUS=$(aws ecs describe-tasks --cluster deployment-cluster --tasks $TASK_ARN --query 'tasks[0].lastStatus' --output text)
 
-          echo "ECS Task Status: $TASK_STATUS"
+      #     echo "ECS Task Status: $TASK_STATUS"
 
-          if [ "$TASK_STATUS" != "STOPPED" ]; then
-            exit 1 # Fail the workflow if the task didn't stop successfully
-          fi
-        shell: bash
-        env:
-          AWS_REGION: us-east-1 # Replace with your region
+      #     if [ "$TASK_STATUS" != "STOPPED" ]; then
+      #       exit 1 # Fail the workflow if the task didn't stop successfully
+      #     fi
+      #   shell: bash
+      #   env:
+      #     AWS_REGION: us-east-1 # Replace with your region
         
 
       # - name: Create ECS Service if it doesn't exist
